var tag_names = {
    /* Custom tags from various gedcom-based programs */
    '_AKA': 'Also Known As',
    '_APPLIES_TO': 'Applies To',
    '_DATE_TYPE': 'Type of Date',
    '_DESC_FLAG': 'Show Description',
    '_EMAIL': 'Email Address',
    '_EVENT_DEFN': 'Event Definition',
    '_FSFTID': 'Family Search Family Tree ID',
    '_ITALIC': 'Print in Italics',
    '_LDS': 'Is LDS',
    '_MARNM': 'Married Name',
    '_MASTER': 'In Master Listing',
    '_NAME': 'Name',
    '_NONE': 'No Children',
    '_PAREN': 'Print in Parentheses',
    '_PLACE_TYPE': 'Type of Place',
    '_PRIM': 'Primary Object is Multimedia',
    '_PRIMARY': 'Primary',
    '_RIN': 'Record Identification Number',
    '_ROTATE': 'Rotation Degrees',
    '_SCBK': 'Scrapbook',
    '_SENT': 'Sentence Template',
    '_SSHOW': 'Slideshow',
    '_STIME': 'Slideshow Length',
    '_STAT': 'Status',
    '_TYPE': 'File Type',
    '_UID': 'Universally Unique ID',
    '_UPD': 'Updated',
    /* Standard tags */
    'ABBR': 'Abbreviation',
    'ADDR': 'Address',
    'ADR1': 'Address Line 1',
    'ADR2': 'Address Line 2',
    'ADOP': 'Adoption',
    'AFN':  'Ancestral File Number',
    'AGE':  'Age',
    'AGNC': 'Agency',
    'ALIA': 'Alias',
    'ANCE': 'Ancestors',
    'ANCI': 'Ancestors of Interest',
    'ANUL': 'Annulment',
    'ASSO': 'Associates',
    'AUTH': 'Author',
    'BAPL': 'LDS Baptism',
    'BAPM': 'Baptism',
    'BARM': 'Bar Mitzvah',
    'BASM': 'Bas Mitzvah',
    'BIRT': 'Birth',
    'BLES': 'Blessing',
    'BLOB': 'Binary Large Object',
    'BURI': 'Burial',
    'CALN': 'Call Number',
    'CAST': 'Caste',
    'CAUS': 'Cause',
    'CENS': 'Census',
    'CHAN': 'Change',
    'CHAR': 'Character',
    'CHIL': 'Child',
    'CHR':  'Child Christening',
    'CHRA': 'Adult Christening',
    'CITY': 'City',
    'CONC': 'Concatenation',
    'CONF': 'Confirmation',
    'CONL': 'LDS Confirmation',
    'CONT': 'Continued',
    'COPR': 'Copyright',
    'CORP': 'Corporate',
    'CREM': 'Cremation',
    'CTRY': 'Country',
    'DATA': 'Data',
    'DATE': 'Date',
    'DEAT': 'Death',
    'DESC': 'Descendants',
    'DESI': 'Descendants of Interest',
    'DEST': 'Destination',
    'DIV':  'Divorce',
    'DIVF': 'Divorce Filed',
    'DSCR': 'Physical Description',
    'EDUC': 'Education',
    'EMIG': 'Emigration',
    'ENDL': 'LDS Endowment',
    'ENGA': 'Engagement',
    'EVEN': 'Event',
    'FAM':  'Family',
    'FAMC': 'Child in Family',
    'FAMF': 'Family File',
    'FAMS': 'Spouse in Family',
    'FCOM': 'First Communion',
    'FILE': 'File',
    'FORM': 'Format',
    'GEDC': 'Gedcom',
    'GIVN': 'Given Name',
    'GRAD': 'Graduation',
    'HEAD': 'Header',
    'HUSB': 'Husband',
    'IDNO': 'Identification Number',
    'IMMI': 'Immigration',
    'INDI': 'Individual',
    'LANG': 'Language',
    'LEGA': 'Legatee',
    'MARB': 'Marriage Announcement',
    'MARC': 'Marriage Contract',
    'MARL': 'Marriage License',
    'MARR': 'Marriage',
    'MARS': 'Marriage Settlement',
    'MEDI': 'Media',
    'NAME': 'Name',
    'NATI': 'Nationality',
    'NATU': 'Naturalization',
    'NCHI': 'Number of Children',
    'NICK': 'Nickname',
    'NMR':  'Number of Marriages',
    'NOTE': 'Note',
    'NPFX': 'Name Prefix',
    'NSFX': 'Name Suffix',
    'OBJE': 'Object',
    'OCCU': 'Occupation',
    'ORDI': 'Ordinanace',
    'ORDN': 'Ordination',
    'PAGE': 'Page',
    'PEDI': 'Pedigree',
    'PHON': 'Phone',
    'PLAC': 'Place',
    'POST': 'Postal Code',
    'PROB': 'Probate',
    'PROP': 'Property',
    'PUBL': 'Publication',
    'QUAY': 'Quality of Data',
    'REFN': 'Reference',
    'RELA': 'Relationship',
    'RELI': 'Religion',
    'REPO': 'Repository',
    'RESI': 'Residence',
    'RESN': 'Restriction',
    'RETI': 'Retirement',
    'RFN':  'Record File Number',
    'RIN':  'Record Id Number',
    'ROLE': 'Role',
    'SEX':  'Sex',
    'SLGC': 'Sealing to Parents',
    'SLGS': 'Sealing to Spouse',
    'SOUR': 'Source',
    'SPFX': 'Surname Prefix',
    'SSN':  'Social Security Number',
    'STAE': 'State',
    'STAT': 'US State',
    'SUBM': 'Submitter',
    'SUBN': 'Submission',
    'SURN': 'Surname',
    'TEMP': 'Temple',
    'TEXT': 'Text',
    'TIME': 'Time',
    'TITL': 'Title',
    'TRLR': 'Trailer',
    'TYPE': 'Type',
    'VERS': 'Version',
    'WIFE': 'Wife',
    'WILL': 'Will',
};
module.exports = tag_names;
