var temple_codes = {
  "ABA": "Aba Nigeria",
  "ACCRA": "Accra Ghana",
  "ADELA": "Adelaide Australia",
  "ALBER": "Cardston Alberta",
  "AL": "Cardston Alberta",
  "ALBUQ": "Albuquerque New Mexico",
  "ANCHO": "Anchorage Alaska",
  "APIA": "Apia Samoa",
  "AP": "Apia Samoa",
  "ARIZO": "Mesa Arizona",
  "AZ": "Mesa Arizona",
  "ASUNC": "Asunci\u00f3n Paraguay",
  "ATLAN": "Atlanta Georgia",
  "AT": "Atlanta Georgia",
  "BAIRE": "Buenos Aires Argentina",
  "BA": "Buenos Aires Argentina",
  "BILLI": "Billings Montana",
  "BIRMI": "Birmingham Alabama",
  "BISMA": "Bismarck North Dakota",
  "BOGOT": "Bogot\u00e1 Colombia",
  "BG": "Bogot\u00e1 Colombia",
  "BOISE": "Boise Idaho",
  "BO": "Boise Idaho",
  "BOSTO": "Boston Massachusetts",
  "BOUNT": "Bountiful Utah",
  "BRIGH": "Brigham City Utah",
  "BRISB": "Brisbane Australia",
  "BROUG": "Baton Rouge Louisiana",
  "CALGA": "Calgary Alberta",
  "CAMPI": "Campinas Brazil",
  "CARAC": "Caracas Venezuela",
  "CEBUP": "Cebu Philippines",
  "CHICA": "Chicago Illinois",
  "CH": "Chicago Illinois",
  "CIUJU": "Ciudad Ju\u00e1rez M\u00e9xico",
  "COCHA": "Cochabamba Bolivia",
  "COLJU": "Colonia Ju\u00e1rez Chihuahua M\u00e9xico",
  "COLSC": "Columbia South Carolina",
  "COLUM": "Columbus Ohio",
  "COPEN": "Copenhagen Denmark",
  "CORDO": "Cordoba Argentina",
  "CRIVE": "Columbia River Washington",
  "CURIT": "Curitiba Brazil",
  "DALLA": "Dallas Texas",
  "DA": "Dallas Texas",
  "DENVE": "Denver Colorado",
  "DV": "Denver Colorado",
  "DETRO": "Detroit Michigan",
  "DRAPE": "Draper Utah",
  "EDMON": "Edmonton Alberta",
  "EHOUS": "Endowment House",
  "EH": "Endowment House",
  "FORTL": "Fort Lauderdale Florida",
  "FRANK": "Frankfurt Germany",
  "FR": "Frankfurt Germany",
  "FREIB": "Freiberg Germany",
  "FD": "Freiberg Germany",
  "FRESN": "Fresno California",
  "FUKUO": "Fukuoka Japan",
  "GILAV": "The Gila Valley Arizona",
  "GILBE": "Gilbert Arizona",
  "GUADA": "Guadalajara M\u00e9xico",
  "GUATE": "Guatemala City Guatemala",
  "GA": "Guatemala City Guatemala",
  "GUAYA": "Guayaquil Ecuador",
  "GY": "Guayaquil Ecuador",
  "HAGUE": "The Hague Netherlands",
  "HALIF": "Halifax Nova Scotia",
  "HAWAI": "Laie Hawaii",
  "HA": "Laie Hawaii",
  "HELSI": "Helsinki Finland",
  "HERMO": "Hermosillo Sonora M\u00e9xico",
  "HKONG": "Hong Kong China",
  "HOUST": "Houston Texas",
  "IFALL": "Idaho Falls Idaho",
  "IF": "Idaho Falls Idaho",
  "INDIA": "Indianapolis Indiana",
  "JOHAN": "Johannesburg South Africa",
  "JO": "Johannesburg South Africa",
  "JRIVE": "Jordan River Utah",
  "JR": "Jordan River Utah",
  "KANSA": "Kansas City Missouri",
  "KONA": "Kona Hawaii",
  "KYIV": "Kyiv Ukraine",
  "LANGE": "Los Angeles California",
  "LA": "Los Angeles California",
  "LIMA": "Lima Peru",
  "LI": "Lima Peru",
  "LOGAN": "Logan Utah",
  "LG": "Logan Utah",
  "LONDO": "London England",
  "LD": "London England",
  "LOUIS": "Louisville Kentucky",
  "LUBBO": "Lubbock Texas",
  "LVEGA": "Las Vegas Nevada",
  "LV": "Las Vegas Nevada",
  "MADRI": "Madrid Spain",
  "MANAU": "Manaus Brazil",
  "MANHA": "Manhattan New York",
  "MANIL": "Manila Philippines",
  "MA": "Manila Philippines",
  "MANTI": "Manti Utah",
  "MT": "Manti Utah",
  "MEDFO": "Medford Oregon",
  "MELBO": "Melbourne Australia",
  "MEMPH": "Memphis Tennessee",
  "MERID": "M\u00e9rida M\u00e9xico",
  "MEXIC": "M\u00e9xico City M\u00e9xico",
  "MX": "M\u00e9xico City M\u00e9xico",
  "MNTVD": "Montevideo Uruguay",
  "MONTE": "Monterrey M\u00e9xico",
  "MONTI": "Monticello Utah",
  "MONTR": "Montr\u00e9al Qu\u00e9bec",
  "MITMP": "Mount Timpanogos Utah",
  "MTIMP": "Mount Timpanogos Utah",
  "NASHV": "Nashville Tennessee",
  "NAUV": "Nauvoo Illinois",
  "NAUV2": "Nauvoo Illinois",
  "NAUVO": "Nauvoo Illinois",
  "NBEAC": "Newport Beach California",
  "NUKUA": "Nuku'alofa Tonga",
  "TG": "Nuku'alofa Tonga",
  "NZEAL": "Hamilton New Zealand",
  "NZ": "Hamilton New Zealand",
  "OAKLA": "Oakland California",
  "OK": "Oakland California",
  "OAXAC": "Oaxaca M\u00e9xico",
  "OGDEN": "Ogden Utah",
  "OG": "Ogden Utah",
  "OKLAH": "Oklahoma City Oklahoma",
  "OQUIR": "Oquirrh Mountain Utah",
  "ORLAN": "Orlando Florida",
  "OTHER": "Unknown Temple",
  "PALEG": "Porto Alegre Brazil",
  "PALMY": "Palmyra New York",
  "PANAM": "Panam\u00e1 City Panam\u00e1",
  "PAPEE": "Papeete Tahiti",
  "TA": "Papeete Tahiti",
  "PERTH": "Perth Australia",
  "PHOEN": "Phoenix Arizona",
  "POFFI": "President's Office",
  "PORTL": "Portland Oregon",
  "PT": "Portland Oregon",
  "PREST": "Preston England",
  "PROVO": "Provo Utah",
  "PV": "Provo Utah",
  "QUETZ": "Quetzaltenango Guatemala",
  "RALEI": "Raleigh North Carolina",
  "RECIF": "Recife Brazil",
  "REDLA": "Redlands California",
  "REGIN": "Regina Saskatchewan",
  "RENO": "Reno Nevada",
  "REXBU": "Rexburg Idaho",
  "SACRA": "Sacramento California",
  "SANSA": "San Salvador El Salvador",
  "SANTI": "Santiago Chile",
  "SN": "Santiago Chile",
  "SANTO": "San Antonio Texas",
  "SDIEG": "San Diego California",
  "SA": "San Diego California",
  "SDOMI": "Santo Domingo Dominican Republic",
  "SEATT": "Seattle Washington",
  "SE": "Seattle Washington",
  "SEOUL": "Seoul Korea",
  "SO": "Seoul Korea",
  "SGEOR": "St. George Utah",
  "SG": "St. George Utah",
  "SJOSE": "San Jos\u00e9 Costa Rica",
  "SLAKE": "Salt Lake City Utah",
  "SL": "Salt Lake City Utah",
  "SLOUI": "St. Louis Missouri",
  "SNOWF": "Snowflake Arizona",
  "SPAUL": "S\u00e3o Paulo Brazil",
  "SP": "S\u00e3o Paulo Brazil",
  "SPMIN": "St. Paul Minnesota",
  "SPOKA": "Spokane Washington",
  "STOCK": "Stockholm Sweden",
  "ST": "Stockholm Sweden",
  "SUVA": "Suva Fiji",
  "SWISS": "Bern Switzerland",
  "SW": "Bern Switzerland",
  "SYDNE": "Sydney Australia",
  "SD": "Sydney Australia",
  "TAIPE": "Taipei Taiwan",
  "TP": "Taipei Taiwan",
  "TAMPI": "Tampico M\u00e9xico",
  "TEGUC": "Tegucigalpa Honduras",
  "TGUTI": "Tuxtla Guti\u00e9rrez M\u00e9xico",
  "TOKYO": "Tokyo Japan",
  "TK": "Tokyo Japan",
  "TORON": "Toronto Ontario",
  "TR": "Toronto Ontario",
  "TRUJI": "Trujillo Peru",
  "TWINF": "Twin Falls Idaho",
  "VANCO": "Vancouver British Columbia",
  "VERAC": "Veracruz M\u00e9xico",
  "VERNA": "Vernal Utah",
  "VILLA": "Villahermosa M\u00e9xico",
  "WASHI": "Washington D.C.",
  "WA": "Washington D.C.",
  "WINTE": "Winter Quarters"
};

module.exports = temple_codes;